# Generated by Django 2.2.7 on 2019-11-10 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshpublickey',
            old_name='key',
            new_name='ssh_public_key',
        ),
        migrations.AlterUniqueTogether(
            name='sshpublickey',
            unique_together={('user', 'fingerprint')},
        ),
    ]
