# Generated by Django 2.2.7 on 2019-11-10 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20191110_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshpublickey',
            options={'permissions': (('can_assign_device', 'Can Assign Device to SShPublicKey'),)},
        ),
        migrations.AlterModelOptions(
            name='sshpublickeytokeygroup',
            options={'permissions': (('can_aprove_assignment', 'Can confirm aprove'),)},
        ),
        migrations.AddField(
            model_name='sshpublickeytokeygroup',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sshpublickeytokeygroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
