# Generated by Django 2.2.7 on 2019-11-10 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20191110_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='keygroup',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='sshpublickey',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='sshpublickey',
            unique_together={('created_by', 'fingerprint')},
        ),
    ]
