# Generated by Django 2.2.7 on 2019-11-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_sshpublickey_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sshpublickeytokeygroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='sshpublickeytokeygroup',
            name='aproved',
        ),
    ]
