# Generated by Django 2.2.7 on 2019-11-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191117_1958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sshpublickeytokeygroup',
            unique_together={('ssh_public_key', 'key_group')},
        ),
    ]
