# Generated by Django 2.2.7 on 2019-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191110_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('gitlab', 'Gitlab'), ('github', 'Github')], max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
