# Generated by Django 3.0 on 2020-01-25 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userarea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminarea', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_visibility', models.BooleanField(default=False)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_visibility', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminarea.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_visibility', models.BooleanField(default=False)),
                ('name', models.SlugField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminarea.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ssh_private_key', models.TextField(max_length=2000)),
                ('fingerprint', models.CharField(max_length=512)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('created_by', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='HostToHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizational_visibility', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superarea.HostGroup')),
                ('host_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superarea.Host')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminarea.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='private_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superarea.PrivateKey'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superarea.HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminarea.Organization'),
        ),
        migrations.CreateModel(
            name='UserToPublishGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('publish_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superarea.PublishGroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group', 'publish_group')},
            },
        ),
        migrations.CreateModel(
            name='PublishGroupToKeyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userarea.KeyGroup')),
                ('publish_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superarea.PublishGroup')),
            ],
            options={
                'unique_together': {('publish_group', 'key_group')},
            },
        ),
    ]
