# Generated by Django 2.2.7 on 2019-12-09 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertopublishgroup',
            old_name='publishgroup',
            new_name='group',
        ),
        migrations.AlterUniqueTogether(
            name='usertopublishgroup',
            unique_together={('user', 'group', 'publish_group')},
        ),
    ]
