# Generated by Django 2.2.7 on 2019-11-16 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0002_server_sshprivatekey_usertopublishgroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertopublishgroup',
            unique_together={('user', 'group', 'publish_group')},
        ),
    ]
