# Generated by Django 2.2.7 on 2019-12-11 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0002_auto_20191209_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishgrouptokeygroup',
            name='aproved',
        ),
        migrations.AlterField(
            model_name='oauth2integration',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OAuth2IntegrationToPublishGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('oauth2_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.OAuth2Integration')),
                ('publish_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.PublishGroup')),
            ],
        ),
    ]
