# Generated by Django 2.2.7 on 2019-12-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_auto_20191211_1640'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oauth2integrationtopublishgroup',
            unique_together={('oauth2_integration', 'publish_group')},
        ),
    ]
