# Generated by Django 2.2.7 on 2019-12-12 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0004_auto_20191211_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Server',
            new_name='Host',
        ),
        migrations.CreateModel(
            name='HostToHostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.HostGroup')),
                ('host_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publish.Host')),
            ],
        ),
    ]
