# Generated by Django 2.2.7 on 2019-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='datatype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'string'), (1, 'boolean'), (2, 'number'), (3, 'datetime'), (4, 'option')]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
