# Generated by Django 2.2.7 on 2019-11-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=255)),
                ('datatype', models.PositiveSmallIntegerField(choices=[(0, 'string'), (1, 'boolean'), (2, 'number'), (3, 'datetime'), (4, 'option')])),
                ('default', models.TextField()),
                ('description', models.TextField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
