# Generated by Django 3.0 on 2020-01-25 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminarea', '0001_initial'),
        ('superarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appintegrationtopublishgroup',
            name='publish_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superarea.PublishGroup'),
        ),
        migrations.AddField(
            model_name='appintegration',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appintegration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminarea.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='appintegrationtopublishgroup',
            unique_together={('app_integration', 'publish_group')},
        ),
    ]
