# Generated by Django 3.0 on 2020-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminarea', '0002_auto_20200116_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appintegration',
            name='access_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appintegration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appintegration',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
